eureka:
  client:
    registerWithEureka:
      value: true
    fetchRegistry:
      value: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
  